baseURL = "http://localhost/at4-hugo"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "at4Theme"
disableHugoGeneratorInject = true

publishDir= "C:\\inetpub\\wwwroot\\at4-hugo"


[outputs]
    section = ["html", "json", "amp"] # al contener <amp-story> hay que poder generear el json del bookend (list.amp.html + list.json)
    home = ["html", "amp"]
    page = ["html", "amp"]