name = "At4Theme"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://at4.net/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Joan Josep Escandell Riera"
  homepage = "http://at4.het"
